# -*- coding: utf-8 -*-
ULKE_BILGI = {
    "turkiye": ("tr", "turkey"), "katar": ("ar", "qatar"), "misir": ("ar", "egypt"),
    "romanya": ("ro", "romania"), "vietnam": ("vi", "vietnam"), "arjantin": ("es", "argentina"),
    "almanya": ("de", "germany"), "fransa": ("fr", "france"), "hollanda": ("nl", "netherlands"),
    "isvec": ("sv", "sweden"), "bae": ("ar", "united arab emirates"), "suudi_arabistan": ("ar", "saudi arabia"),
    "isvicre": ("de", "switzerland"), "avusturya": ("de", "austria"), "kirgizistan": ("ru", "kyrgyzstan"),
    "moldova": ("ro", "moldova"), "finlandiya": ("fi", "finland"), "slovenya": ("sl", "slovenia"),
    "belcika": ("nl", "belgium"), "birlesik_krallik": ("en", "united kingdom"), "hindistan": ("en", "india"),
    "kanada": ("en", "canada"), "avustralya": ("en", "australia"), "irlanda": ("en", "ireland"),
    "guney_afrika": ("en", "south africa"), "brezilya": ("pt", "brazil"), "meksika": ("es", "mexico"),
    "kazakistan": ("ru", "kazakhstan"), "ozbekistan": ("ru", "uzbekistan"), "polonya": ("pl", "poland"),
    "bulgaristan": ("bg", "bulgaria"), "singapur": ("en", "singapore"), "abd": ("en", "united states"),
    "cin": ("zh", "china"), "azerbaycan": ("ru", "azerbaijan"), "estonya": ("et", "estonia"),
    "ispanya": ("es", "spain"), "italya": ("it", "italy"), "portekiz": ("pt", "portugal"),
    "japonya": ("ja", "japan"), "maldivler": ("en", "maldives"), "bosna_hersek": ("bs", "bosnia and herzegovina"),
    "sirbistan": ("sr", "serbia"), "karadag": ("sr", "montenegro"), "arnavutluk": ("sq", "albania"),
    "gurcistan": ("ka", "georgia"), "endonezya": ("id", "indonesia"), "guney_kore": ("ko", "south korea"),
    "norvec": ("no", "norway"), "danimarka": ("da", "denmark"), "sili": ("es", "chile"),
    "yeni_zelanda": ("en", "new zealand"), "tayland": ("th", "thailand"), "tayvan": ("zhtw", "taiwan"),
    "rusya": ("ru", "russia"), "malezya": ("ms", "malaysia"), "yunanistan": ("el", "greece"),
    "izlanda": ("is", "iceland"), "fas": ("ar", "morocco"), "cekya": ("cs", "czech republic"),
    "litvanya": ("lt", "lithuania"), "macaristan": ("hu", "hungary"), "uruguay": ("es", "uruguay"),
    "filipinler": ("en", "philippines"),
}

DIL_SORGULARI = {
    "ar": ["مسابقة تكنولوجية", "معرض تكنولوجي", "مؤتمر تكنولوجي", "ورشة ريادة الأعمال",
           "فعالية تكنولوجية", "هاكاثون", "داتاثون", "ايديثون", "برنامج تسريع",
           "برنامج ريادة الأعمال", "برنامج منح", "برنامج استثمار",
           "مسابقة ابتكار حكومية", "مسابقة طلابية جامعية", "مسابقة تكنولوجيا وزارة الدفاع",
           "مسابقة وكالة الفضاء", "هاكاثون برعاية شركات", "منحة ابتكار القطاع العام",
           "دعوة مفتوحة لمعهد أبحاث", "دعوة ابتكار ممولة من الاتحاد الأوروبي"],
    "ro": ["competitie tehnologica", "targ de tehnologie", "congres de tehnologie", "atelier de antreprenoriat",
           "eveniment tehnologic", "hackathon", "datathon", "ideathon", "program de accelerare",
           "program de antreprenoriat", "program de granturi", "program de investitii",
           "competitie guvernamentala de inovare", "competitie studenteasca universitara", "competitie tehnologica minister apararii",
           "competitie agentie spatiala", "hackathon sponsorizat corporativ", "grant de inovare sector public",
           "apel deschis institut de cercetare", "apel de inovare finantat UE"],
    "vi": ["cuoc thi cong nghe", "hoi cho cong nghe", "hoi nghi cong nghe", "hoi thao khoi nghiep",
           "su kien cong nghe", "hackathon", "datathon", "ideathon", "chuong trinh tang toc",
           "chuong trinh khoi nghiep", "chuong trinh tai tro", "chuong trinh dau tu",
           "cuoc thi doi moi sang tao chinh phu", "cuoc thi sinh vien dai hoc", "cuoc thi cong nghe bo quoc phong",
           "cuoc thi co quan vu tru", "hackathon tai tro doanh nghiep", "tai tro doi moi khu vuc cong",
           "loi keu goi mo cua vien nghien cuu", "loi keu goi doi moi tai tro boi EU"],
    "es": ["competencia tecnologica", "feria tecnologica", "congreso tecnologico", "taller de emprendimiento",
           "evento tecnologico", "hackathon", "datathon", "ideathon", "programa de aceleracion",
           "programa de emprendimiento", "programa de subvenciones", "programa de inversion",
           "concurso gubernamental de innovacion", "concurso universitario estudiantil", "concurso tecnologico del ministerio de defensa",
           "concurso agencia espacial", "hackathon patrocinado por empresas", "subvencion de innovacion del sector publico",
           "convocatoria abierta instituto de investigacion", "convocatoria de innovacion financiada por la UE"],
    "de": ["Technologiewettbewerb", "Technologiemesse", "Technologiekongress", "Gruender-Workshop",
           "Technologieveranstaltung", "Hackathon", "Datathon", "Ideathon", "Beschleunigerprogramm",
           "Gruenderprogramm", "Foerderprogramm", "Investitionsprogramm",
           "staatlicher Innovationswettbewerb", "Universitats-Studentenwettbewerb", "Technologiewettbewerb Verteidigungsministerium",
           "Raumfahrtagentur-Wettbewerb", "unternehmensgesponserter Hackathon", "Innovationsfoerderung oeffentlicher Sektor",
           "offener Aufruf Forschungsinstitut", "EU-finanzierter Innovationsaufruf"],
    "fr": ["concours technologique", "salon technologique", "congres technologique", "atelier d'entrepreneuriat",
           "evenement technologique", "hackathon", "datathon", "ideathon", "programme d'acceleration",
           "programme d'entrepreneuriat", "programme de subvention", "programme d'investissement",
           "concours d'innovation gouvernemental", "concours etudiant universitaire", "concours technologique ministere de la defense",
           "concours agence spatiale", "hackathon parraine par des entreprises", "subvention d'innovation secteur public",
           "appel ouvert institut de recherche", "appel a l'innovation finance par l'UE"],
    "nl": ["technologiewedstrijd", "technologiebeurs", "technologiecongres", "ondernemerschapsworkshop",
           "technologie-evenement", "hackathon", "datathon", "ideathon", "acceleratieprogramma",
           "ondernemerschapsprogramma", "subsidieprogramma", "investeringsprogramma",
           "overheids-innovatiewedstrijd", "universitaire studentenwedstrijd", "technologiewedstrijd ministerie van defensie",
           "ruimtevaartagentschap wedstrijd", "door bedrijven gesponsorde hackathon", "innovatiesubsidie publieke sector",
           "open oproep onderzoeksinstituut", "door EU gefinancierde innovatieoproep"],
    "sv": ["tekniktavling", "teknikmassa", "teknikkongress", "entreprenorskapsworkshop",
           "teknikevenemang", "hackathon", "datathon", "ideathon", "acceleratorprogram",
           "entreprenorskapsprogram", "bidragsprogram", "investeringsprogram",
           "statlig innovationstavling", "universitets studenttavling", "forsvarsdepartementets teknologitavling",
           "rymdstyrelsens tavling", "foretagssponsrad hackathon", "innovationsbidrag offentlig sektor",
           "oppen utlysning forskningsinstitut", "EU-finansierad innovationsutlysning"],
    "ru": ["tehnologicheskiy konkurs", "tehnologicheskaya vystavka", "tehnologicheskiy kongress", "seminar po predprinimatelstvu",
           "tehnologicheskoe sobytie", "hakaton", "dataton", "ideaton", "programma akseleratsii",
           "programma predprinimatelstva", "grantovaya programma", "investitsionnaya programma",
           "gosudarstvenniy konkurs innovatsiy", "studencheskiy universitetskiy konkurs", "konkurs ministerstva oborony po tehnologiyam",
           "konkurs kosmicheskogo agentstva", "hakaton pri podderzhke kompaniy", "grant na innovatsii v gossektore",
           "otkritiy konkurs issledovatelskogo instituta", "konkurs innovatsiy finansiruemiy ES"],
    "fi": ["teknologiakilpailu", "teknologiamessut", "teknologiakongressi", "yrittajyystyopaja",
           "teknologiatapahtuma", "hackathon", "datathon", "ideathon", "kiihdytinohjelma",
           "yrittajyysohjelma", "apurahaohjelma", "sijoitusohjelma",
           "valtion innovaatiokilpailu", "yliopiston opiskelijakilpailu", "puolustusministerion teknologiakilpailu",
           "avaruusjarjeston kilpailu", "yritysten sponsoroima hackathon", "julkisen sektorin innovaatioapuraha",
           "tutkimuslaitoksen avoin haku", "EU-rahoitteinen innovaatiohaku"],
    "sl": ["tehnoloski natecaj", "tehnoloski sejem", "tehnoloski kongres", "delavnica podjetnistva",
           "tehnoloski dogodek", "hekaton", "datathon", "ideathon", "pospesevalni program",
           "program podjetnistva", "program donacij", "investicijski program",
           "vladno inovacijsko tekmovanje", "univerzitetno studentsko tekmovanje", "tehnoloski natecaj ministrstva za obrambo",
           "tekmovanje vesoljske agencije", "hekaton sponzoriran s strani podjetij", "inovacijska donacija javnega sektorja",
           "odprti razpis raziskovalnega instituta", "EU financiran inovacijski razpis"],
    "pt": ["competicao tecnologica", "feira de tecnologia", "congresso de tecnologia", "workshop de empreendedorismo",
           "evento tecnologico", "hackathon", "datathon", "ideathon", "programa de aceleracao",
           "programa de empreendedorismo", "programa de subvencoes", "programa de investimento",
           "concurso governamental de inovacao", "concurso universitario estudantil", "concurso tecnologico do ministerio da defesa",
           "concurso agencia espacial", "hackathon patrocinado por empresas", "subvencao de inovacao do setor publico",
           "chamada aberta de instituto de pesquisa", "chamada de inovacao financiada pela UE"],
    "pl": ["konkurs technologiczny", "targi technologiczne", "kongres technologiczny", "warsztaty przedsiebiorczosci",
           "wydarzenie technologiczne", "hackathon", "datathon", "ideathon", "program akceleracyjny",
           "program przedsiebiorczosci", "program grantowy", "program inwestycyjny",
           "rzadowy konkurs innowacji", "konkurs studencki uniwersytecki", "konkurs technologiczny ministerstwa obrony",
           "konkurs agencji kosmicznej", "hackathon sponsorowany przez firmy", "grant innowacyjny sektora publicznego",
           "otwarty nabor instytutu badawczego", "wezwanie do innowacji finansowane przez UE"],
    "bg": ["tehnologichno saostezanie", "tehnologichen panair", "tehnologichen kongres", "rabotilnitsa za predpriemachestvo",
           "tehnologichno sabitie", "hakaton", "dataton", "ideaton", "programa za akseleratsiya",
           "programa za predpriemachestvo", "grant programa", "investitsionna programa",
           "darzhavno saostezanie za inovatsii", "universitetsko studentsko saostezanie", "tehnologichno saostezanie na ministerstvo na otbranata",
           "saostezanie na kosmicheska agentsiya", "hakaton sponsoriran ot kompanii", "grant za inovatsii v publichniya sektor",
           "otvorena pokana na izsledovatelski institut", "finansirana ot ES pokana za inovatsii"],
    "zh": ["技术比赛", "技术展会", "技术大会", "创业工作坊",
           "科技活动", "黑客马拉松", "数据松", "创意松", "加速器项目",
           "创业项目", "资助项目", "投资项目",
           "政府创新挑战赛", "大学生挑战赛", "国防部技术挑战赛",
           "航天局挑战赛", "企业赞助黑客马拉松", "公共部门创新资助",
           "研究机构公开征集", "欧盟资助创新征集"],
    "et": ["tehnoloogiakonkurss", "tehnoloogiamess", "tehnoloogiakongress", "ettevotluse tootuba",
           "tehnoloogiasundmus", "hackathon", "datathon", "ideathon", "kiirendiprogramm",
           "ettevotlusprogramm", "toetusprogramm", "investeerimisprogramm",
           "valitsuse innovatsioonikonkurss", "ulikooli tudengikonkurss", "kaitseministeeriumi tehnoloogiakonkurss",
           "kosmoseagentuuri konkurss", "ettevotete sponsoreeritud hackathon", "avaliku sektori innovatsioonitoetus",
           "teadusinstituudi avatud konkurss", "EL rahastatud innovatsioonikonkurss"],
    "it": ["competizione tecnologica", "fiera tecnologica", "congresso tecnologico", "workshop di imprenditorialita",
           "evento tecnologico", "hackathon", "datathon", "ideathon", "programma di accelerazione",
           "programma di imprenditorialita", "programma di sovvenzioni", "programma di investimento",
           "concorso governativo di innovazione", "concorso universitario studentesco", "concorso tecnologico ministero della difesa",
           "concorso agenzia spaziale", "hackathon sponsorizzato da aziende", "sovvenzione innovazione settore pubblico",
           "bando aperto istituto di ricerca", "bando innovazione finanziato UE"],
    "ja": ["技術コンテスト", "技術展示会", "技術会議", "起業ワークショップ",
           "技術イベント", "ハッカソン", "データソン", "アイデアソン", "アクセラレータープログラム",
           "起業家プログラム", "助成金プログラム", "投資プログラム",
           "政府イノベーションチャレンジ", "大学生チャレンジ", "防衛省技術チャレンジ",
           "宇宙機関チャレンジ", "企業協賛ハッカソン", "公共部門イノベーション助成金",
           "研究機関公募", "EU資金イノベーション公募"],
    "bs": ["tehnoloski natjecaj", "tehnoloski sajam", "tehnoloski kongres", "radionica poduzetnistva",
           "tehnoloski dogadaj", "hakaton", "datathon", "ideathon", "program akceleracije",
           "program poduzetnistva", "program grantova", "investicijski program",
           "vladino natjecanje za inovacije", "univerzitetsko studentsko natjecanje", "tehnoloski natjecaj ministarstva odbrane",
           "natjecanje svemirske agencije", "hakaton sponzorisan od kompanija", "grant za inovacije javnog sektora",
           "otvoreni poziv istrazivackog instituta", "poziv za inovacije finansiran od EU"],
    "sr": ["tehnoloski takmicenje", "tehnoloski sajam", "tehnoloski kongres", "radionica preduzetnistva",
           "tehnoloski dogadjaj", "hakaton", "datathon", "ideathon", "program akceleracije",
           "program preduzetnistva", "program grantova", "investicioni program",
           "vladino takmicenje za inovacije", "univerzitetsko studentsko takmicenje", "tehnoloski takmicenje ministarstva odbrane",
           "takmicenje svemirske agencije", "hakaton sponzorisan od kompanija", "grant za inovacije javnog sektora",
           "otvoreni poziv istrazivackog instituta", "poziv za inovacije finansiran od EU"],
    "sq": ["konkurs teknologjik", "panair teknologjik", "kongres teknologjik", "punetori sipermarrjeje",
           "ngjarje teknologjike", "hakaton", "datathon", "ideathon", "program akselerimi",
           "program sipermarrjeje", "program grantesh", "program investimi",
           "konkurs qeveritar inovacioni", "konkurs universitar studentor", "konkurs teknologjik i ministrise se mbrojtjes",
           "konkurs agjencie hapesinore", "hakaton i sponsorizuar nga kompani", "grant inovacioni i sektorit publik",
           "thirrje e hapur instituti kerkimor", "thirrje inovacioni e financuar nga BE"],
    "ka": ["teknologiuri konkursi", "teknologiuri gamofena", "teknologiuri kongresi", "mewarmeobis vorksopi",
           "teknologiuri gharigheva", "hakatoni", "datatoni", "ideatoni", "amaghmarthebuli programa",
           "mewarmeobis programa", "granturi programa", "sainvestitsio programa",
           "mtavrobis inovatsiuri konkursi", "universitetis studentta konkursi", "tavdatsvis saministros teknologiuri konkursi",
           "kosmosuri saagentos konkursi", "korporatsiebi mier daxmarebuli hakatoni", "sajaro seqtoris inovatsiuri granti",
           "sameqmedo institutis ghia mowveva", "evrokavshiris dafinansebuli inovatsiuri mowveva"],
    "id": ["kompetisi teknologi", "pameran teknologi", "kongres teknologi", "lokakarya kewirausahaan",
           "acara teknologi", "hackathon", "datathon", "ideathon", "program akselerasi",
           "program kewirausahaan", "program hibah", "program investasi",
           "kompetisi inovasi pemerintah", "kompetisi mahasiswa universitas", "kompetisi teknologi kementerian pertahanan",
           "kompetisi badan antariksa", "hackathon disponsori perusahaan", "hibah inovasi sektor publik",
           "panggilan terbuka lembaga penelitian", "panggilan inovasi didanai UE"],
    "ko": ["기술 대회", "기술 박람회", "기술 학회", "창업 워크숍",
           "기술 이벤트", "해커톤", "데이터톤", "아이디어톤", "액셀러레이터 프로그램",
           "창업 프로그램", "보조금 프로그램", "투자 프로그램",
           "정부 혁신 챌린지", "대학생 챌린지", "국방부 기술 챌린지",
           "우주국 챌린지", "기업 후원 해커톤", "공공 부문 혁신 보조금",
           "연구기관 공개 공모", "EU 지원 혁신 공모"],
    "no": ["teknologikonkurranse", "teknologimesse", "teknologikongress", "entreprenorskapsverksted",
           "teknologiarrangement", "hackathon", "datathon", "ideathon", "akseleratorprogram",
           "entreprenorskapsprogram", "tilskuddsprogram", "investeringsprogram",
           "statlig innovasjonskonkurranse", "universitets studentkonkurranse", "forsvarsdepartementets teknologikonkurranse",
           "romfartsorganisasjonens konkurranse", "bedriftssponset hackathon", "innovasjonstilskudd offentlig sektor",
           "apen utlysning forskningsinstitutt", "EU-finansiert innovasjonsutlysning"],
    "da": ["teknologikonkurrence", "teknologimesse", "teknologikongres", "ivaerksaetterworkshop",
           "teknologibegivenhed", "hackathon", "datathon", "ideathon", "acceleratorprogram",
           "ivaerksaetterprogram", "tilskudsprogram", "investeringsprogram",
           "statslig innovationskonkurrence", "universitets studenterkonkurrence", "forsvarsministeriets teknologikonkurrence",
           "rumagenturs konkurrence", "virksomhedssponsoreret hackathon", "offentlig sektor innovationstilskud",
           "abent opslag forskningsinstitut", "EU-finansieret innovationsopslag"],
    "th": ["kan khaengkhan technology", "ngan sadaeng technology", "kan prachum technology", "workshop phu prakop kan",
           "kittikam technology", "hackathon", "datathon", "ideathon", "khrongkan ekselerater",
           "khrongkan phu prakop kan", "khrongkan thun sanapsanoon", "khrongkan longthun",
           "kan khaengkhan nawatakam ratthaban", "kan khaengkhan naksueksa mahawitthayalai", "kan khaengkhan technology krasuang kalahom",
           "kan khaengkhan ongkan udomsuksa", "hackathon thi ban ing doi borisat", "thun sanapsanoon nawatakam phak rat",
           "kan riakrong poet sathaban wichai", "kan riakrong nawatakam thun uu doi EU"],
    "zhtw": ["科技競賽", "科技展覽", "科技大會", "創業工作坊",
             "科技活動", "駭客松", "數據松", "點子松", "加速器計畫",
             "創業計畫", "補助計畫", "投資計畫",
             "政府創新挑戰賽", "大學生挑戰賽", "國防部科技挑戰賽",
             "太空總署挑戰賽", "企業贊助駭客松", "公部門創新補助",
             "研究機構公開徵件", "歐盟資助創新徵件"],
    "ms": ["pertandingan teknologi", "pameran teknologi", "kongres teknologi", "bengkel keusahawanan",
           "acara teknologi", "hackathon", "datathon", "ideathon", "program pemecutan",
           "program keusahawanan", "program geran", "program pelaburan",
           "pertandingan inovasi kerajaan", "pertandingan pelajar universiti", "pertandingan teknologi kementerian pertahanan",
           "pertandingan agensi angkasa", "hackathon ditaja syarikat", "geran inovasi sektor awam",
           "panggilan terbuka institut penyelidikan", "panggilan inovasi dibiayai EU"],
    "el": ["technologikos diagonismos", "technologiki ekthesi", "technologiko synedrio", "ergastirio epicheirimatikotitas",
           "technologiki ekdilosi", "hackathon", "datathon", "ideathon", "programma epitachynsis",
           "programma epicheirimatikotitas", "programma epichorigisis", "programma ependyseon",
           "kyverntikos diagonismos kainotomias", "foititikos panepistimiakos diagonismos", "technologikos diagonismos ypourgeiou amynas",
           "diagonismos diastimikou organismou", "hackathon me chorigia etaireion", "epichorigisi kainotomias dimosiou tomea",
           "anoichti prosklisi ereynitikou institutou", "prosklisi kainotomias chrimatodotoumeni apo EE"],
    "is": ["taeknikeppni", "taeknisyning", "taeknithing", "frumkvodlasmidja",
           "taekniviðburður", "hackathon", "datathon", "ideathon", "hradunarforrit",
           "frumkvodlaforrit", "styrkjaforrit", "fjarfestingarforrit",
           "nyskopunarkeppni stjornvalda", "haskolanema keppni", "taeknikeppni varnarmalaraduneytisins",
           "keppni geimferdastofnunar", "hackathon studd af fyrirtaekjum", "nyskopunarstyrkur opinbera geirans",
           "opid utbod rannsoknarstofnunar", "nyskopunarutbod fjarmagnad af ESB"],
    "cs": ["technologicka soutez", "technologicky veletrh", "technologicky kongres", "workshop podnikani",
           "technologicka udalost", "hackathon", "datathon", "ideathon", "akceleracni program",
           "program podnikani", "grantovy program", "investicni program",
           "vladni soutez o inovace", "univerzitni studentska soutez", "technologicka soutez ministerstva obrany",
           "soutez vesmirne agentury", "hackathon sponzorovany firmami", "inovacni grant verejneho sektoru",
           "otevrena vyzva vyzkumneho ustavu", "inovacni vyzva financovana EU"],
    "lt": ["technologiju konkursas", "technologiju paroda", "technologiju kongresas", "verslumo seminaras",
           "technologiju renginys", "hakatonas", "datatonas", "ideatonas", "akceleravimo programa",
           "verslumo programa", "dotaciju programa", "investiciju programa",
           "vyriausybes inovaciju konkursas", "universiteto studentu konkursas", "gynybos ministerijos technologiju konkursas",
           "kosmoso agenturos konkursas", "imoniu remiamas hakatonas", "viesojo sektoriaus inovaciju dotacija",
           "atviras tyrimu instituto kvietimas", "ES finansuojamas inovaciju kvietimas"],
    "hu": ["technologiai verseny", "technologiai vasar", "technologiai kongresszus", "vallalkozoi workshop",
           "technologiai esemeny", "hackathon", "datathon", "ideathon", "gyorsito program",
           "vallalkozoi program", "tamogatasi program", "befektetesi program",
           "kormanyzati innovacios verseny", "egyetemi hallgatoi verseny", "vedelmi miniszterium technologiai versenye",
           "urugynokseg versenye", "vallalatok altal szponzoralt hackathon", "kozszfera innovacios tamogatas",
           "kutatointezet nyilt palyazata", "EU altal finanszirozott innovacios felhivas"],
}
